apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  labels:
    app: {{ .Release.Name }}-nginx
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  app_mode: {{ .Values.configData.app_mode | quote }}
  log_level: {{ .Values.configData.log_level | quote }}
